Repository zero323/pyspark-stubs, pull requests merged in 2019-09, with the labels that each got.

#205 Add static annotations for pyspark.status
  README.rst
  third_party/3/pyspark/status.pyi
Labels: 2.3, 2.4, 3.0, enhancement

#216 Reflect removals introduced in SPARK-28980
  third_party/3/pyspark/__init__.pyi
  third_party/3/pyspark/mllib/clustering.pyi
  third_party/3/pyspark/sql/__init__.pyi
  third_party/3/pyspark/sql/catalog.pyi
  third_party/3/pyspark/sql/context.pyi
Labels: 3.0

#229 Support `int` type for the parameter `truncate` in `DataFrame.show`
  third_party/3/pyspark/sql/dataframe.pyi
Labels: 2.3, 2.4, 3.0, enhancement

#233 Add multiple column support to QuantileDiscretizer
  third_party/3/pyspark/ml/feature.pyi
Labels: 3.0

#232 Overload StringIndexer __init__ and setParams
  test-data/unit/ml-feature.test
  tests/unit/testpyspark.py
  third_party/3/pyspark/ml/feature.pyi
Labels: 3.0

#236 Add multiple column support to Bucketizer
  third_party/3/pyspark/ml/feature.pyi
Labels: 3.0

#238 Mark ML initalizers and setParams as keyword only
  third_party/3/pyspark/ml/classification.pyi
  third_party/3/pyspark/ml/clustering.pyi
  third_party/3/pyspark/ml/evaluation.pyi
  third_party/3/pyspark/ml/feature.pyi
  third_party/3/pyspark/ml/fpm.pyi
  third_party/3/pyspark/ml/pipeline.pyi
  third_party/3/pyspark/ml/recommendation.pyi
  third_party/3/pyspark/ml/regression.pyi
  third_party/3/pyspark/ml/tuning.pyi
Labels: 2.4

#239 Mark ML initalizers and setParams as keyword only
  third_party/3/pyspark/ml/classification.pyi
  third_party/3/pyspark/ml/clustering.pyi
  third_party/3/pyspark/ml/evaluation.pyi
  third_party/3/pyspark/ml/feature.pyi
  third_party/3/pyspark/ml/fpm.pyi
  third_party/3/pyspark/ml/pipeline.pyi
  third_party/3/pyspark/ml/recommendation.pyi
  third_party/3/pyspark/ml/regression.pyi
  third_party/3/pyspark/ml/tuning.pyi
Labels: 2.3

#237 Mark ML initalizers and setParams as keyword only
  test-data/unit/ml-feature.test
  third_party/3/pyspark/ml/classification.pyi
  third_party/3/pyspark/ml/clustering.pyi
  third_party/3/pyspark/ml/evaluation.pyi
  third_party/3/pyspark/ml/feature.pyi
  third_party/3/pyspark/ml/fpm.pyi
  third_party/3/pyspark/ml/pipeline.pyi
  third_party/3/pyspark/ml/recommendation.pyi
  third_party/3/pyspark/ml/regression.pyi
  third_party/3/pyspark/ml/tuning.pyi
Labels: 3.0

#243 SPARK-29258 parity between ml.evaluator and mllib.metrics
  third_party/3/pyspark/ml/evaluation.pyi
Labels: 3.0

#252 Add leafCol to DecisionTreeParams
  third_party/3/pyspark/ml/regression.pyi
Labels: 3.0

#256 Make Params generic (branch 2.4)
  test-data/unit/ml-param.test
  tests/unit/testpyspark.py
  third_party/3/pyspark/ml/classification.pyi
  third_party/3/pyspark/ml/clustering.pyi
  third_party/3/pyspark/ml/evaluation.pyi
  third_party/3/pyspark/ml/feature.pyi
  third_party/3/pyspark/ml/fpm.pyi
  third_party/3/pyspark/ml/param/__init__.pyi
  third_party/3/pyspark/ml/param/shared.pyi
  third_party/3/pyspark/ml/recommendation.pyi
  third_party/3/pyspark/ml/regression.pyi
  third_party/3/pyspark/ml/tuning.pyi
Labels: 2.4
